# Generated by Django 4.2.6 on 2023-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_machine', '0002_alter_report_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.FloatField(),
        ),
    ]
